name: flight_booking_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #iOS style icons
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  fluentui_system_icons: ^1.1.273
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true


  assets:
    - lib/assets/images/profile.jpg
    - lib/assets/images/city_view.png
    - lib/assets/images/hotel_room.png
    - lib/assets/images/logo.png
    - lib/assets/images/plane_sit.jpg
    - lib/assets/images/pool_view.png
    - lib/assets/images/visa_card.png
    - lib/assets/images/visa_card.png
    - lib/assets/appUi

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
